### ISSUE TITLE
Extra Quotation

### ISSUE THREAD

**Issue by creightonjoiner** [johnkerl/pangram-checker#1]
https://github.com/johnkerl/pangram-checker/blob/13b31bde50e569b3c8930ccbdc128ce0bc331e81/index.html#L17

`<a href="https://en.wikipedia.org/wiki/Pangram"">pangram</a>`

When comparing the code here and what is on the published site there seems to be an extra double quote in there. It causes the link to not go directly to the wikipedia page.

**Comment by johnkerl** [comment]
:)

**Comment by johnkerl** [comment]
Fixed in #2 -- thank you @creightonjoiner !
